WIFI_SSID = ''
WIFI_PASSWORD = ''

EMAIL_ADDRESS = ''
EMAIL_TOKEN = ''

TELEGRAM_TOKEN = ''
TELEGRAM_CHAT_ID = ''

INFLUX_URL = 'http:// <IP ADDRESS> :8086/api/v2/write?org= <YOUR ORG> &bucket= <YOUR BUCKET> &precision=s'
INFLUX_TOKEN = 'Token <YOUR TOKEN HERE>'