# Autogenerated file
def render(*a, **d):
    yield """﻿"""
    page = 'cam'
    yield """
"""
# Autogenerated file
    def render1(*a, **d):
        yield """<!DOCTYPE html>

<html lang=\"en\">
<head>
    <meta charset=\"utf-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">    
    <title>Garage Monitor</title>
    <link rel=\"icon\" type=\"image/x-icon\" href=\"static/images/favicon.png\">
    <link rel=\"stylesheet\" href=\"static/css/index.css\">
    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>
    """
        if page == 'home':
            yield """
    <script src=\"https://cdn.plot.ly/plotly-2.16.1.min.js\"></script>
    <script src=\"static/js/warning_coloring.js\"></script>
    <script src=\"static/js/home.js\"></script>
    """
        elif page == 'sensors':
            yield """
    <script src=\"static/js/warning_coloring.js\"></script>
    <script src=\"static/js/sensors.js\"></script>
    """
        elif page == 'clock':
            yield """
    <script src=\"static/js/clock.js\"></script>
    """
        yield """
</head>

<body>
<div class=\"sidebar\">
  <a href=\"/\">Home</a>
  <a href=\"/sensors\">All Sensors</a>
  <a href=\"/dash\">Network Dashboard</a>
  <a href=\"/cam\">Cameras</a>
  <a href=\"/clock\">Clock</a>

  <div id=\"side_mem\">
    <label id=\"mem_meter_label\" for=\"mem_meter\"></label><br>
    <meter id=\"mem_meter\" min=0 max=1 high=0.75></meter>
  </div>
</div>"""
    yield from render1()
    yield """

<div class=\"content\">
  <iframe src=\"http://10.222.5.130:8090/\" width=\"100%\" height=\"100%\" style=\"border:none;\"></iframe>
</div>

</body>
</html>"""
